substitutions:
  device_name: blinds
  friendly_name: Loungeroom Blinds
  cover_name: Loungeroon Blinds Cover

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

external_components:
  - source:
      type: local
      path: external_components
    components: [position_based]

esp32:
  board: um_pros3

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    # not setting SSID uses device name 
    password: !secret ap_password

captive_portal:

sensor:
  - platform: adc
    pin: GPIO10
    name: Battery voltage ${friendly_name}
    accuracy_decimals: 3
    attenuation: 6dB
    filters:
      - multiply: 3.79
  - platform: adc
    pin: GPIO6
    internal: true
    id: position # 10K linear pot plus 10k resistor to 3v3. gives 0-1.65v, requires 6db attenuation
    unit_of_measurement: "%"
    state_class: "measurement"
    accuracy_decimals: 3
    attenuation: 6dB
    update_interval: 0.2s
    filters:
      - calibrate_linear: # this is for setting the max and min positions. Also can reverse the direction to save re-soldering
        - 0.2 -> 1.0
        - 1.6 -> 0.0

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO15
      mode:
        input: true
        pullup: true
      inverted: true
    id: motor_fault
    name: Motor Fault ${friendly_name}
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

switch:
  - platform: gpio
    pin: GPIO17    #PRO-S3 3v3 2nd LDO - power saving in sleep
    name: Power Output ${friendly_name}
    restore_mode: ALWAYS_ON

output:
  - platform: ledc
    pin: GPIO13
    id: ina_output
    frequency: 300hz
  - platform: ledc
    pin: GPIO12
    id: inb_output
    frequency: 300hz
  - platform: gpio
    pin: GPIO14
    id: sleep_output

fan:
  - platform: hbridge
    id: motor
    internal: true
    pin_a: ina_output
    pin_b: inb_output
    decay_mode: slow   # slow decay mode (braking) or fast decay (coasting) 

cover:
  - platform: position_based
    name: ${cover_name}
    id: blinds_cover
    position_sensor: position
    max_duration: 20s
    disengage_time: 1.2s
    open_action:
      - output.turn_on: sleep_output
      - fan.turn_on: 
          id: motor
          direction: reverse
          speed: 85
    close_action:
      - output.turn_on: sleep_output
      - fan.turn_on: 
          id: motor
          direction: forward
          speed: 85
    stop_action:
      - fan.turn_off: motor
      - output.turn_off: sleep_output
