esphome:
  name: makerpower-mppt

substitutions:
  disp_name: makerpower-mppt
  update_time: 10s
  
external_components:
  - source:
      type: local
      path: external_components
    components: [mppt]
    
      
esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxxx"

ota:
  password: "xxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Makerpower-Mppt Fallback Hotspot"
    password: "xxxx"

captive_portal:
    

i2c:
  sda: GPIO4
  scl: GPIO5
  
sensor:
  - platform: wifi_signal
    name: ${disp_name} WiFi Signal
    update_interval: 60s
  - platform: mppt
    solar_voltage:
      name: ${disp_name} Solar Voltage
    solar_current:
      name: ${disp_name} Solar Current
    solar_power:
      name: ${disp_name} Solar Power
    battery_voltage:
      name: ${disp_name} Battery Voltage
    load_current:
      name: ${disp_name} Load Current
    load_power:
      name: ${disp_name} Load Power    
    charge_current:
      name: ${disp_name} Charge Current
    charge_power:
      name: ${disp_name} Charge Power  
    charger_temperature:
      name: ${disp_name} Charger Temperature
    battery_temperature:
      name: ${disp_name} Battery Temperature
    mppt_target_voltage:
      name: ${disp_name} MPPT Target Voltage
    charge_target_voltage:
      name: ${disp_name} Charge Target Voltage
    buck_pwm:
      name: ${disp_name} Charger PWM
    system_status:
      name: ${disp_name} Charger Status

